/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2016-04-18 03:03:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSPs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    \n");
      out.write("    <title>User Signin page</title>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap Core CSS -->\n");
      out.write("    <link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Custom CSS: You can use this stylesheet to override any Bootstrap styles and/or apply your own styles -->\n");
      out.write("    <link href=\"../css/login.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>\n");
      out.write("    \n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <!-- Navigation -->\n");
      out.write("    <nav id=\"siteNav\" class=\"navbar navbar-default navbar-fixed-top\" role=\"navigation\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <!-- Logo and responsive toggle -->\n");
      out.write("            <div class=\"navbar-header\">\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#navbar\">\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                </button>\n");
      out.write("                <a class=\"navbar-brand\" href=\"#\">\n");
      out.write("                    <span class=\"glyphicon glyphicon-fire\"></span> \n");
      out.write("                    STORE\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("            <!-- Navbar links -->\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbar\">\n");
      out.write("                <ul class=\"nav navbar-nav navbar-center\">\n");
      out.write("                    <li class=\"active\">\n");
      out.write("                        <a href=\"../index.html\"><font color=\"black\"><b>Home</b></font></a>\n");
      out.write("                    </li>\n");
      out.write("                   \n");
      out.write("                </ul>\n");
      out.write("                \n");
      out.write("            </div><!-- /.navbar-collapse -->\n");
      out.write("        </div><!-- /.container -->\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <!-- Header -->\n");
      out.write("    <header>\n");
      out.write("        <div class=\"header-content\">\n");
      out.write("            <div class=\"header-content-inner\">\n");
      out.write("                <form>\n");
      out.write("                <h1><font color= #cc6600>New User</font></h1>\n");
      out.write("\t\t<p><font color=#cc6600><b>Username:</b></font>\n");
      out.write("\t\t<input type=\"text\" name=\"username\"> </p>\n");
      out.write("\t\t<br>\n");
      out.write("\t\t<p><font color=#cc6600><b>Role</b></font>\n");
      out.write("\t\t<select name=\"role\">\n");
      out.write("\t\t\t<option value=\"owner\">owner</option>\n");
      out.write("\t\t\t<option value=\"customer\">customer</option>\n");
      out.write("\t\t</select> </p>\n");
      out.write("\t\t<br> \n");
      out.write("\t\t<p><font color=#cc6600><b>Age</b></font>\n");
      out.write("\t\t<input type=\"text\" name=\"age\"> </p>\n");
      out.write("\t\t<br>\n");
      out.write("\t\t<p><font color=#cc6600><b>State</b></font>\n");
      out.write("\t\t<select name=\"state\">\n");
      out.write("\t\t\t<option value=\"AL\">Alabama</option>\n");
      out.write("\t\t\t<option value=\"AK\">Alaska</option>\n");
      out.write("\t\t\t<option value=\"AZ\">Arizona</option>\n");
      out.write("\t\t\t<option value=\"AR\">Arkansas</option>\n");
      out.write("\t\t\t<option value=\"CA\">California</option>\n");
      out.write("\t\t\t<option value=\"CO\">Colorado</option>\n");
      out.write("\t\t\t<option value=\"CT\">Connecticut</option>\n");
      out.write("\t\t\t<option value=\"DE\">Delaware</option>\n");
      out.write("\t\t\t<option value=\"DC\">District Of Columbia</option>\n");
      out.write("\t\t\t<option value=\"FL\">Florida</option>\n");
      out.write("\t\t\t<option value=\"GA\">Georgia</option>\n");
      out.write("\t\t\t<option value=\"HI\">Hawaii</option>\n");
      out.write("\t\t\t<option value=\"ID\">Idaho</option>\n");
      out.write("\t\t\t<option value=\"IL\">Illinois</option>\n");
      out.write("\t\t\t<option value=\"IN\">Indiana</option>\n");
      out.write("\t\t\t<option value=\"IA\">Iowa</option>\n");
      out.write("\t\t\t<option value=\"KS\">Kansas</option>\n");
      out.write("\t\t\t<option value=\"KY\">Kentucky</option>\n");
      out.write("\t\t\t<option value=\"LA\">Louisiana</option>\n");
      out.write("\t\t\t<option value=\"ME\">Maine</option>\n");
      out.write("\t\t\t<option value=\"MD\">Maryland</option>\n");
      out.write("\t\t\t<option value=\"MA\">Massachusetts</option>\n");
      out.write("\t\t\t<option value=\"MI\">Michigan</option>\n");
      out.write("\t\t\t<option value=\"MN\">Minnesota</option>\n");
      out.write("\t\t\t<option value=\"MS\">Mississippi</option>\n");
      out.write("\t\t\t<option value=\"MO\">Missouri</option>\n");
      out.write("\t\t\t<option value=\"MT\">Montana</option>\n");
      out.write("\t\t\t<option value=\"NE\">Nebraska</option>\n");
      out.write("\t\t\t<option value=\"NV\">Nevada</option>\n");
      out.write("\t\t\t<option value=\"NH\">New Hampshire</option>\n");
      out.write("\t\t\t<option value=\"NJ\">New Jersey</option>\n");
      out.write("\t\t\t<option value=\"NM\">New Mexico</option>\n");
      out.write("\t\t\t<option value=\"NY\">New York</option>\n");
      out.write("\t\t\t<option value=\"NC\">North Carolina</option>\n");
      out.write("\t\t\t<option value=\"ND\">North Dakota</option>\n");
      out.write("\t\t\t<option value=\"OH\">Ohio</option>\n");
      out.write("\t\t\t<option value=\"OK\">Oklahoma</option>\n");
      out.write("\t\t\t<option value=\"OR\">Oregon</option>\n");
      out.write("\t\t\t<option value=\"PA\">Pennsylvania</option>\n");
      out.write("\t\t\t<option value=\"RI\">Rhode Island</option>\n");
      out.write("\t\t\t<option value=\"SC\">South Carolina</option>\n");
      out.write("\t\t\t<option value=\"SD\">South Dakota</option>\n");
      out.write("\t\t\t<option value=\"TN\">Tennessee</option>\n");
      out.write("\t\t\t<option value=\"TX\">Texas</option>\n");
      out.write("\t\t\t<option value=\"UT\">Utah</option>\n");
      out.write("\t\t\t<option value=\"VT\">Vermont</option>\n");
      out.write("\t\t\t<option value=\"VA\">Virginia</option>\n");
      out.write("\t\t\t<option value=\"WA\">Washington</option>\n");
      out.write("\t\t\t<option value=\"WV\">West Virginia</option>\n");
      out.write("\t\t\t<option value=\"WI\">Wisconsin</option>\n");
      out.write("\t\t\t<option value=\"WY\">Wyoming</option>\n");
      out.write("\t\t</select> </p>\n");
      out.write("\t\t<br>\n");
      out.write("\t\t<a href=\"MainPage.jsp\" class=\"btn btn-primary btn-lg\">Sign Up</a>\n");
      out.write("\t</form>\n");
      out.write("            </div>\n");
      out.write("        </div> \n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("  \n");
      out.write("    <footer class=\"page-footer\">\n");
      out.write("    \n");
      out.write("\n");
      out.write("        <div class=\"small-print\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <p>Copyright &copy;Whatever  2016</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("    <!-- jQuery -->\n");
      out.write("    <script src=\"js/jquery-1.11.3.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap Core JavaScript -->\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Plugin JavaScript -->\n");
      out.write("    <script src=\"js/jquery.easing.min.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- Custom Javascript -->\n");
      out.write("    <script src=\"js/custom.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
