/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2016-04-18 00:44:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSPs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>signup</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<form>\n");
      out.write("\t\tUsername: <input type=\"text\" name=\"username\"> \n");
      out.write("\t\t<br>\n");
      out.write("\t\tRole:\n");
      out.write("\t\t<select name=\"role\">\n");
      out.write("\t\t\t<option value=\"owner\">owner</option>\n");
      out.write("\t\t\t<option value=\"customer\">customer</option>\n");
      out.write("\t\t</select> \n");
      out.write("\t\t<br> \n");
      out.write("\t\tAge: <input type=\"text\" name=\"age\"> \n");
      out.write("\t\t<br>\n");
      out.write("\t\tState: <select name=\"state\">\n");
      out.write("\t\t\t<option value=\"AL\">Alabama</option>\n");
      out.write("\t\t\t<option value=\"AK\">Alaska</option>\n");
      out.write("\t\t\t<option value=\"AZ\">Arizona</option>\n");
      out.write("\t\t\t<option value=\"AR\">Arkansas</option>\n");
      out.write("\t\t\t<option value=\"CA\">California</option>\n");
      out.write("\t\t\t<option value=\"CO\">Colorado</option>\n");
      out.write("\t\t\t<option value=\"CT\">Connecticut</option>\n");
      out.write("\t\t\t<option value=\"DE\">Delaware</option>\n");
      out.write("\t\t\t<option value=\"DC\">District Of Columbia</option>\n");
      out.write("\t\t\t<option value=\"FL\">Florida</option>\n");
      out.write("\t\t\t<option value=\"GA\">Georgia</option>\n");
      out.write("\t\t\t<option value=\"HI\">Hawaii</option>\n");
      out.write("\t\t\t<option value=\"ID\">Idaho</option>\n");
      out.write("\t\t\t<option value=\"IL\">Illinois</option>\n");
      out.write("\t\t\t<option value=\"IN\">Indiana</option>\n");
      out.write("\t\t\t<option value=\"IA\">Iowa</option>\n");
      out.write("\t\t\t<option value=\"KS\">Kansas</option>\n");
      out.write("\t\t\t<option value=\"KY\">Kentucky</option>\n");
      out.write("\t\t\t<option value=\"LA\">Louisiana</option>\n");
      out.write("\t\t\t<option value=\"ME\">Maine</option>\n");
      out.write("\t\t\t<option value=\"MD\">Maryland</option>\n");
      out.write("\t\t\t<option value=\"MA\">Massachusetts</option>\n");
      out.write("\t\t\t<option value=\"MI\">Michigan</option>\n");
      out.write("\t\t\t<option value=\"MN\">Minnesota</option>\n");
      out.write("\t\t\t<option value=\"MS\">Mississippi</option>\n");
      out.write("\t\t\t<option value=\"MO\">Missouri</option>\n");
      out.write("\t\t\t<option value=\"MT\">Montana</option>\n");
      out.write("\t\t\t<option value=\"NE\">Nebraska</option>\n");
      out.write("\t\t\t<option value=\"NV\">Nevada</option>\n");
      out.write("\t\t\t<option value=\"NH\">New Hampshire</option>\n");
      out.write("\t\t\t<option value=\"NJ\">New Jersey</option>\n");
      out.write("\t\t\t<option value=\"NM\">New Mexico</option>\n");
      out.write("\t\t\t<option value=\"NY\">New York</option>\n");
      out.write("\t\t\t<option value=\"NC\">North Carolina</option>\n");
      out.write("\t\t\t<option value=\"ND\">North Dakota</option>\n");
      out.write("\t\t\t<option value=\"OH\">Ohio</option>\n");
      out.write("\t\t\t<option value=\"OK\">Oklahoma</option>\n");
      out.write("\t\t\t<option value=\"OR\">Oregon</option>\n");
      out.write("\t\t\t<option value=\"PA\">Pennsylvania</option>\n");
      out.write("\t\t\t<option value=\"RI\">Rhode Island</option>\n");
      out.write("\t\t\t<option value=\"SC\">South Carolina</option>\n");
      out.write("\t\t\t<option value=\"SD\">South Dakota</option>\n");
      out.write("\t\t\t<option value=\"TN\">Tennessee</option>\n");
      out.write("\t\t\t<option value=\"TX\">Texas</option>\n");
      out.write("\t\t\t<option value=\"UT\">Utah</option>\n");
      out.write("\t\t\t<option value=\"VT\">Vermont</option>\n");
      out.write("\t\t\t<option value=\"VA\">Virginia</option>\n");
      out.write("\t\t\t<option value=\"WA\">Washington</option>\n");
      out.write("\t\t\t<option value=\"WV\">West Virginia</option>\n");
      out.write("\t\t\t<option value=\"WI\">Wisconsin</option>\n");
      out.write("\t\t\t<option value=\"WY\">Wyoming</option>\n");
      out.write("\t\t</select> \n");
      out.write("\t\t<br>\n");
      out.write("\t\t<input type=\"submit\" value=\"Signup\">\n");
      out.write("\t</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
